# Generated by Django 2.0.5 on 2018-06-04 16:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bld_time', models.DateTimeField()),
                ('bld_data', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_type', models.CharField(max_length=40)),
                ('f_name', models.CharField(max_length=60)),
                ('f_sz', models.FloatField()),
                ('f_kal', models.FloatField()),
                ('f_car', models.FloatField()),
                ('f_pro', models.FloatField()),
                ('f_fat', models.FloatField()),
                ('f_dang', models.FloatField()),
                ('f_ntr', models.FloatField()),
                ('f_chol', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hos_name', models.CharField(max_length=40)),
                ('hos_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_time', models.DateTimeField()),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ditas.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=40)),
                ('med_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_name', models.CharField(max_length=100)),
                ('news_url', models.TextField(validators=[django.core.validators.URLValidator])),
                ('news_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=5)),
                ('birth_date', models.DateField(null=True)),
                ('height', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_date', models.DateField()),
                ('kg_value', models.FloatField()),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ditas.User')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ditas.User'),
        ),
        migrations.AddField(
            model_name='meal',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ditas.User'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ditas.User'),
        ),
        migrations.AddField(
            model_name='blood',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ditas.User'),
        ),
        migrations.AlterUniqueTogether(
            name='weight',
            unique_together={('u_id', 'kg_date')},
        ),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together={('u_id', 'med_name')},
        ),
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('u_id', 'f_id', 'f_time')},
        ),
        migrations.AlterUniqueTogether(
            name='hospital',
            unique_together={('u_id', 'hos_name')},
        ),
        migrations.AlterUniqueTogether(
            name='blood',
            unique_together={('u_id', 'bld_time')},
        ),
    ]
