# Generated by Django 2.0.5 on 2018-06-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ditas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood',
            old_name='u_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='u_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='u_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='u_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='weight',
            old_name='u_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='blood',
            unique_together={('user', 'bld_time')},
        ),
        migrations.AlterUniqueTogether(
            name='hospital',
            unique_together={('user', 'hos_name')},
        ),
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('user', 'f_id', 'f_time')},
        ),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together={('user', 'med_name')},
        ),
        migrations.AlterUniqueTogether(
            name='weight',
            unique_together={('user', 'kg_date')},
        ),
    ]
