# Generated by Django 2.0.5 on 2018-06-17 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ditas', '0003_auto_20180609_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='food_list',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='meal',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ditas.Food'),
        ),
    ]
